### ISSUE TITLE
ERROR NoneType object is not subscriptable when trying to Attach boot pool mirror

### ISSUE THREAD

**Issue by stuartmcknight** [truenas/middleware#9003]
TrueNAS 13 Core

![image](https://user-images.githubusercontent.com/48601625/169541245-1a146827-556d-40de-aac4-5ba0a4fdce37.png)

Found this in middlewared.log

[2022/05/14 14:52:21] (ERROR) middlewared.job.run():367 - Job <bound method accepts.<locals>.wrap.<locals>.nf of <middlewared.plugins.boot.BootService object at 0x81baa6a90>> failed
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/middlewared/job.py", line 355, in run
await self.future
File "/usr/local/lib/python3.9/site-packages/middlewared/job.py", line 391, in __run_body
rv = await self.method(*([self] + args))
File "/usr/local/lib/python3.9/site-packages/middlewared/schema.py", line 975, in nf
return await f(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/middlewared/plugins/boot.py", line 109, in attach
'path': f'/dev/{zfs_dev_part["name"]}'
TypeError: 'NoneType' object is not subscriptable

**Comment by yocalebo** [comment]
Should already be fixed in 13.0-U1.
